Games
Strukturavaltas-03-Frontend-2022/csapatmunka---snake-game-02-and-world-peace pull request #3
Opened 2022-10-21 09:16 UTC by rekahamburger

feladat megoldás- 1 ső probálkozás

2022-10-21 10:23 UTC, bankiszabolcs commented on src/BaseGame.ts
> +     abstract getRandomLevel(levels: any[]): Level {
protected head: Piece;
  protected tail: Piece;
  protected paused: boolean = false;
  protected food: Piece | null;
  protected goldenApple: Piece | null;
  protected length: number = 0;
  protected growth: number = 0;
  protected score: number = 0;
  protected currentLevel: Level | null;
  protected garden: HTMLDivElement;

2022-10-21 10:27 UTC, bankiszabolcs commented on src/BaseGame.ts
> +
protected head: Piece;
protected tail: Piece;
protected paused: boolean = false;
protected food: Piece | null;
protected goldenApple: Piece | null;
protected length: number = 0;
protected growth: number = 0;
protected score: number = 0;
protected currentLevel: Level | null;
protected garden: HTMLDivElement;

2022-10-21 10:33 UTC, bankiszabolcs commented on src/BaseGame.ts
> +         return rand;
nem kell paraméter
let helyett const
27-es sor nem kell
return this.levels[rand]

2022-10-21 10:35 UTC, bankiszabolcs commented on src/BaseGame.ts
> +     abstract mayIHaveGoldenApple(chance:number, pick:number): boolean{
paraméter!?

2022-10-21 10:35 UTC, bankiszabolcs commented on src/BaseGame.ts
> +
paraméter?

2022-10-21 10:44 UTC, bankiszabolcs commented on src/BaseGame.ts
> +    }
Példa:
const grids: [] = Array.from(document.getElementsByClassName("vertical-grid horizontal-grid"))
VAGY: document.querySelectorAll

2022-10-21 11:00 UTC, bankiszabolcs requested changes
ASD

2022-10-22 11:30 UTC, tamaslud approved these changes
Kösz, ezekkel a módosításokkal szerintem jó lesz!

2022-10-22 11:30 UTC, merged